
// USER
export const FETCH_PLAYERS = "FETCH_PLAYERS";


// AUTH
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";


// MATCH
export const FETCH_TODAYS_MATCH = "FETCH_TODAYS_MATCH";
export const START_RESUME_MATCH = "START_RESUME_MATCH";


// MESSAGE
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";