
// USER
export const FETCH_PLAYERS = "FETCH_PLAYERS";
export const FETCH_LEAGUE = "FETCH_LEAGUE";


// AUTH
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";


// MATCH
export const FETCH_TODAYS_MATCH = "FETCH_TODAYS_MATCH";
export const START_RESUME_MATCH = "START_RESUME_MATCH";
export const MATCH_NOT_FOUND = "MATCH_NOT_FOUND";
export const SET_MATCH_READY = "SET_MATCH_READY";
export const SCORE_HOLE = "SCORE_HOLE";


// MESSAGE
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


// NOT REALLY USED
export const CLEAR_STATE = "CLEAR_STATE";